### PR TITLE
Decaffeinate Tests

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
This is still a bit work in progress. At this point, I've done all the automated work possible. Now I'm going to comb through each of the files and modify them based on the suggestions left behind by decaffeinate. I wanted to get this in front of your early so I don't spin my wheels too long without feedback / thoughts.

My plan is to extract the test helpers into a new library. I'm more familiar with mocha + chai, so my initial intention was to migrate the current matchers to a chai plugin. If you'd prefer to stick with Jasmine, I'll either extract them to a Jasmine plugin or just borrow your code for my chai plugin.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
I attempted to upgrade to the latest version of Jasmine (2.8). The API for adding matchers changed between the version used by `jasmine-node` and the current version, so it would require a decent overhaul to upgrade them.

**Comment by rpominov** [comment]
Looks good so far! And migrating to mocha also sounds good (in a separate PR though).

**Comment by mAAdhaTTah** [comment]
Fixed up all of the tests based on the suggestions left behind by `decaffeinate`. Most of the changes are removing unnecessary `return` statements. Tests are all still passing.

> And migrating to mocha also sounds good (in a separate PR though).

That's the plan!

**Comment by rpominov** [comment]
Tried on my computer, works fine. Thank you for all the work!

Except you need to `npm run prettify`, I've messed up with travis setup and it was reporting false negative (fixed now in `master`).

Feel free to merge when you think it's ready (you need to accept invite to get write access).

**Comment by mAAdhaTTah** [comment]
Ran prettify and amended. My editor still defaults to adding semicolons.

**Comment by mAAdhaTTah** [comment]
Rebased w/ the travis changes from `master`. Everything passes so going to merge this.

**Pull request merged**
