### PR TITLE
Property: set currentEvent before dispatching it

### PR DESCRIPTION
**Pull request by olivierguerriat**
see https://github.com/rpominov/kefir/issues/127

### CODE REVIEW

**Comment by rpominov** [comment]
Could you also write a test case for this?

**Comment by rpominov** [comment]
Thanks!

**Comment by olivierguerriat** [comment]
Thank you for writing the tests, it would have taken me much longer as I am not familiar with Kefir's test helpers nor with CoffeeScript.

**Comment by rpominov** [comment]
I see, np :)

**Pull request merged**
